### PR TITLE
make build Reproducible (mostly)

### PR DESCRIPTION
**Pull request by hboutemy**
following Maven's guide https://maven.apache.org/guides/mini/guide-reproducible-builds.html

I could not check that the result was fully reproducible, because I can't run rpm
but if you follow instruction to check a rebuild against initial build, I'm pretty sure that most of the output content is reproducible: I'm interested to know what remains not reproducible (I suppose the rpm/deb files...)

### CODE REVIEW

**Comment by hengyunabc** [comment]
Thanks for the PR, but arthas using the `git-commit-id-maven-plugin`: https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/472 . 

May have to wait for the new version of the `git-commit-id-maven-plugin`.

**Comment by hboutemy** [comment]
maybe you won't have 100% reproducible artifacts yet, but are really all binary artifacts impacted by this?
isn't it worth improving now what can be improved to be listed on Reproducible Central https://github.com/jvm-repo-rebuild/reproducible-central with partial reproducibility, and working on next steps after?

**Comment by kylixs** [comment]
@hboutemy Could you update git-commit-id-plugin to the latest version (4.0.1)? Seems to be ready for reproducible builds.
https://github.com/git-commit-id/git-commit-id-maven-plugin/releases/tag/v4.0.1
Also please resolve code conflicts.

**Comment by hboutemy** [comment]
@kylixs done

**Comment by kylixs** [comment]
Add configuration  `<injectAllReactorProjects>true</injectAllReactorProjects>` to git-commit-id-plugin, make all subprojects use the same `git.build.time`.  
But there is still a problem, there is no way to use `project.build.outputTimestamp` for the initial value of `git.build.time`, 
it is always initialized to the current time of the system:  

```
  private void loadBuildVersionAndTimeData(@Nonnull Properties properties) {
    Supplier<String> buildTimeSupplier = () -> {
      Date buildDate = new Date();
      SimpleDateFormat smf = new SimpleDateFormat(dateFormat);
      if (dateFormatTimeZone != null) {
        smf.setTimeZone(TimeZone.getTimeZone(dateFormatTimeZone));
      }
      return smf.format(buildDate);
    };
    maybePut(properties, GitCommitPropertyConstant.BUILD_TIME, buildTimeSupplier);

```

**Comment by kylixs** [comment]
add issue to git-commit-id-maven-plugin : https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/509

**Comment by hboutemy** [comment]
FYI, I added Arthas 3.3.7 release evaluation to reproducible-central https://github.com/jvm-repo-rebuild/reproducible-central/issues/27
the `arthas-git.properties` file generated by git-commit-id-maven-plugin is not reproducible at all

**Comment by hengyunabc** [comment]
@hboutemy Thanks, the next release will be reproducible.

**Pull request merged**
