### PR TITLE
Support profiler command on arm64.

### PR DESCRIPTION
**Pull request by fornaix**
Error when running profiler command on arm64.
```
cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
```
This pr is to fix it.

### CODE REVIEW

**Comment by hengyunabc** [comment]
@fornaix Thanks for the pr, which version of the so files?

**Comment by fornaix** [comment]
@hengyunabc  v1.7.1

**Comment by hengyunabc** [comment]
> @hengyunabc v1.7.1

Did you build this SO file yourself? I didn't find it in the official release files.

https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v1.7.1

**Comment by fornaix** [comment]
@hengyunabc  Yes, I built it myself. Official releases din't provide Linux/AArch64 platform version.

**Comment by kylixs** [comment]
@fornaix please provide a build script with  docker file

**Comment by hengyunabc** [comment]
利用CI，貌似可以构建arm的 lib： https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/ 

https://github.com/hypriot/rpi-mysql/blob/master/.travis.yml

**Comment by kylixs** [comment]
> 利用CI，貌似可以构建arm的 lib： https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/
> 
> https://github.com/hypriot/rpi-mysql/blob/master/.travis.yml

将本地构建相关命令整理好，使用合适的Docker镜像作为基准执行自动构建。在Dockerfile中准备好项目构建环境及源码，执行构建命令产生so文件，复制到外部映射目录即可。

**Comment by fornaix** [comment]
> @fornaix please provide a build script with docker file, use the so file generated by automatic build

ARM64 version has been provided in official releases. Could we just use it?

**Comment by hengyunabc** [comment]
> > @fornaix please provide a build script with docker file, use the so file generated by automatic build
> 
> ARM64 version has been provided in official releases. Could we just use it?

Can you update this PR? I'll check the hash value of the so file.

**Comment by fornaix** [comment]
Ok, updated. 
`async-profiler/libasyncProfiler-linux-aarch64.so` was downloaded from https://github.com/jvm-profiling-tools/async-profiler/releases/download/v1.8.1/async-profiler-1.8.1-linux-aarch64.tar.gz
md5: `6680c2899749061d974a0061c97d403a`

cc, @hengyunabc

**Comment by hengyunabc** [comment]
> Ok, updated.
> `async-profiler/libasyncProfiler-linux-aarch64.so` was downloaded from https://github.com/jvm-profiling-tools/async-profiler/releases/download/v1.8.1/async-profiler-1.8.1-linux-aarch64.tar.gz
> md5: `6680c2899749061d974a0061c97d403a`
> 
> cc, @hengyunabc

Thank you very much.

**Pull request merged**
