### PR TITLE
translated contact us page

### PR DESCRIPTION
**Pull request by sjha2048**
Fixes: #1213 

Signed-off-by: Sahil <sjha200000@gmail.com>

### CODE REVIEW

**Comment by kylixs** [comment]
@sjha2048  Can not mix Chinese and English, should add an en version of contact-us.md. I have doubts about ‘exchange group’, it does n’t seem to be an authentic English vocabulary. How about 'discussion group'?

**Comment by sjha2048** [comment]
Shall I name the new file as contact-us-en.md?

**Comment by kylixs** [comment]
> Shall I name the new file as contact-us-en.md?

No, just the same name, you should put it under the path: site/src/site/sphinx/en

**Comment by kylixs** [comment]
@sjha2048 
Need to add DingTalk download method and simple instructions

**Comment by sjha2048** [comment]
Installation and sign up screenshots would work?

**Comment by sjha2048** [comment]
can you have a look now?

**Comment by sjha2048** [comment]
Hi @kylixs can you please check why the build is failing?

**Comment by hengyunabc** [comment]
@sjha2048 Need to add a link in en/index.md, like:

https://github.com/alibaba/arthas/blob/arthas-all-3.3.2/site/src/site/sphinx/index.md

```
* [QQ群/钉钉群](contact-us.md)
```

**Comment by sjha2048** [comment]
updated

**Pull request merged**
