### PR TITLE
 fix CompletionAdaptor index out of bounds when the token is empty

### PR DESCRIPTION
**Pull request by xuzhiyiYoh**
When command line is empty,  use complete will throw out of bounds exception.

### CODE REVIEW

**Comment by xuzhiyiYoh** [comment]
`01 2019-03-29 21:16:01.510 ERROR [nioEventLoopGroup-2-2:arthas] [] [] [] completion error
java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[na:1.8.0_172]
	at java.util.LinkedList.get(LinkedList.java:476) ~[na:1.8.0_172]
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309) ~[na:1.8.0_172]
	at com.taobao.arthas.core.shell.term.impl.CompletionAdaptor.complete(CompletionAdaptor.java:46) ~[arthas-core.jar:3.1.1-SNAPSHOT]
	at com.taobao.arthas.core.shell.system.impl.InternalCommandManager.completeCommands(InternalCommandManager.java:92) ~[arthas-core.jar:3.1.1-SNAPSHOT]
	at com.taobao.arthas.core.shell.system.impl.InternalCommandManager.complete(InternalCommandManager.java:69) ~[arthas-core.jar:3.1.1-SNAPSHOT]
	at com.taobao.arthas.core.shell.handlers.shell.CommandManagerCompletionHandler.handle(CommandManagerCompletionHandler.java:19) ~[arthas-core.jar:3.1.1-SNAPSHOT]
	at com.taobao.arthas.core.shell.handlers.shell.CommandManagerCompletionHandler.handle(CommandManagerCompletionHandler.java:10) ~[arthas-core.jar:3.1.1-SNAPSHOT]
	at com.taobao.arthas.core.shell.term.impl.CompletionHandler.accept(CompletionHandler.java:36) [arthas-core.jar:3.1.1-SNAPSHOT]
	at com.taobao.arthas.core.shell.term.impl.CompletionHandler.accept(CompletionHandler.java:20) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.readline.functions.Complete.apply(Complete.java:39) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.readline.Readline$Interaction.handle(Readline.java:264) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.readline.Readline$Interaction.access$200(Readline.java:189) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.readline.Readline.deliver(Readline.java:123) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.readline.Readline.access$500(Readline.java:41) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.readline.Readline$Interaction$2.accept(Readline.java:427) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.readline.Readline$Interaction$2.accept(Readline.java:421) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.tty.TtyEventDecoder.accept(TtyEventDecoder.java:93) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.tty.TtyEventDecoder.accept(TtyEventDecoder.java:26) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.tty.ReadBuffer.accept(ReadBuffer.java:44) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.tty.ReadBuffer.accept(ReadBuffer.java:28) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.io.BinaryDecoder.write(BinaryDecoder.java:117) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.io.BinaryDecoder.write(BinaryDecoder.java:65) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.telnet.TelnetTtyConnection.onData(TelnetTtyConnection.java:139) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.telnet.TelnetConnection.flushData(TelnetConnection.java:267) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.telnet.TelnetConnection.flushDataIfNecessary(TelnetConnection.java:257) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.telnet.TelnetConnection.receive(TelnetConnection.java:108) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.termd.core.telnet.netty.TelnetChannelHandler.channelRead(TelnetChannelHandler.java:46) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [arthas-core.jar:3.1.1-SNAPSHOT]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [arthas-core.jar:3.1.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]`

**Comment by xuzhiyiYoh** [comment]
image

**Comment by xuzhiyiYoh** [comment]
[#564](https://github.com/alibaba/arthas/issues/564)

**Comment by hengyunabc** [comment]
Thank you very much.

**Pull request merged**
