### PR TITLE
Initial files for Debian Package.

### PR DESCRIPTION
**Pull request by sjha2048**
This Pull request is for creating the Debian package for arthas and this is all of my initial files.

for testing the package run 

### mvn clean install 

this will create arthas.deb inside /packaging/target directory which can be installed by dpkg.

### CODE REVIEW

**Comment by hengyunabc** [comment]
Add `dir` format in `packaging/src/main/assembly/assembly.xml`, then the deb plugin can package files from the directory? No need to configure multiple items. 

```xml
   <formats>
     <format>zip</format>
    <format>dir</format>
   </formats>
```

**Comment by sjha2048** [comment]
I tried this approach but I am facing several build errors in this method like file permission issues and target directory location, but instead of configuring multiple items I'll try to make a template type of package, will update you on this till tomorrow morning

**Comment by hengyunabc** [comment]
Need to update `packaging/src/main/assembly/assembly.xml`

```
   <formats>
+    <format>dir</format>
     <format>zip</format>
   </formats>
```

**Comment by sjha2048** [comment]
Will do it!

**Comment by hengyunabc** [comment]
travis-ci fixed.

**Comment by sjha2048** [comment]
thank you @hengyunabc

**Pull request merged**
