### PR TITLE
watch command support print access point

### PR DESCRIPTION
**Pull request by superheizai**
#1629
1. add the method related class and method info to the output of watch
2. add ENTER/EXIT/EXCEPTION for the output

### CODE REVIEW

**Comment by superheizai** [comment]
will like this
[BEFORE]method=com.example.demo.arthas.TestService$$EnhancerBySpringCGLIB$$18d50546.test
ts=2020-12-16 18:22:58; [cost=0.48057ms] result=@ArrayList[
    @Object[][
        @String[normal],
        @Integer[1],
        @User[
            id=@Integer[1],
            name=@String[Name],
        ],
    ],
    null,
]

**Comment by hengyunabc** [comment]
这个PR的想法挺好的，可能概念上和 bytekit里对齐更好。 `AtEnter`, `AtExit`, `AtExceptionExit`

https://github.com/alibaba/bytekit/blob/0.0.2/bytekit-core/src/main/java/com/alibaba/bytekit/asm/interceptor/annotation/AtEnter.java

**Comment by superheizai** [comment]
已经修改成了AtEnter、AtExit和AtExceptionExit，和ByteKit保持一致

**Comment by hengyunabc** [comment]
改进了下输出位置，放到行尾，避免不对齐：

```
method=demo.MathGame.primeFactors location=AtExceptionExit
ts=2021-01-08 01:17:09; [cost=0.028833ms] result=@ArrayList[
    @Object[][isEmpty=false;size=1],
    @MathGame[demo.MathGame@20ad9418],
    null,
]
method=demo.MathGame.run location=AtExit
ts=2021-01-08 01:17:09; [cost=0.469182ms] result=@ArrayList[
    @Object[][isEmpty=true;size=0],
    @MathGame[demo.MathGame@20ad9418],
    null,
]
```

**Pull request merged**
