### PR TITLE
README-minor-changes.md

### PR DESCRIPTION
**Pull request by ktz72**
Some improvements in Grammer of Documentation

### CODE REVIEW

**Comment by ktz72** [comment]
Some minor faults in grammar I came across

**Comment by Hearen** [comment]
@ralf0131 LGTM 👍

**Comment by Hearen** [comment]
> Some minor faults in grammar I came across

@ktz72 Why? 😕 It's good 😄

**Comment by ktz72** [comment]
@Hearen  Just thought it can be improvised .. :)

**Comment by ktz72** [comment]
@Hearen And about closing, that part .. you see I'm new to Git and this is like my first pull request. So, I kind of doesn't even know what I'm doing.

**Comment by ktz72** [comment]
> > @Hearen And about closing, that part .. you see I'm new to Git and this is like my first pull request. So, I kind of doesn't even know what I'm doing.
> 
> @ktz72 😆 nice check. You can open it to let us merge it 👍

@Hearen  Done. Reopened :)

**Pull request merged**
