### PR TITLE
Test cases for DateUtils.java

### PR DESCRIPTION
**Pull request by brijeshprasad89**
Test cases for DateUtils.java

### CODE REVIEW

**Comment by ralf0131** [comment]
Hi, thanks for the pull request, would you please sign the CLA first?

**Comment by brijeshprasad89** [comment]
> Hi, thanks for the pull request, would you please sign the CLA first?

@ralf0131  I have signed it already. But it does not get reflected in the checks above. PFA the screenshot for your reference. Or can you help me in doing the same
screen shot 2018-10-07 at 9 29 44 pm

**Comment by ralf0131** [comment]
Hi, I think you should make sure your author information in the commit remain the same as the Github user you've logged in to sign the CLA. Would you please confirm that?

**Comment by brijeshprasad89** [comment]
Hi,
I checked it. I think it's. It the same. No idea what to do next.

**Comment by brijeshprasad89** [comment]
It's not the same. Maybe some issue due to my local git config

**Comment by ralf0131** [comment]
Could you please try to re-commit with the Github user information?

**Comment by brijeshprasad89** [comment]
Hi All,

Closing this and creating a new pull request. As my config has some issues.

**Pull request closed without merging**
