### PR TITLE
Doc with consistent demo

### PR DESCRIPTION
**Pull request by Hearen**
Please do not merge this **PM**, I will finish it before tomorrow. Thank you, man 😄

### CODE REVIEW

**Comment by Hearen** [comment]
@hengyunabc Through updating the whole doc, I found several obvious [bugs](https://github.com/Hearen/arthas/issues). I will update them here when I am available. But I think you should know it before that, since they can be re-produced easily with the new [**demo**](https://github.com/alibaba/arthas/blob/fd0f49391a0766357db574d608570a48b28245e5/site/src/site/sphinx/en/quick-start.md) I added in the current doc update.

**Comment by ralf0131** [comment]
Hi, 

First thanks for your passion on the Arthas project. 

I would be better to let the community know your proposal before start contributing.

> Through updating the whole doc, I found several obvious bugs. 

Please report these bugs directly to the community.

I think the correct way should be: file a bug -> send a pull request against that.

**Comment by Hearen** [comment]
> Hi,
> 
> First thanks for your passion on the Arthas project.
> 
> I would be better to let the community know your proposal before start contributing.
> 
> > Through updating the whole doc, I found several obvious bugs.
> 
> Please report these bugs directly to the community.
> 
> I think the correct way should be: file a bug -> send a pull request against that.

@ralf0131 Yes, of course. But as I mentioned, I think I have to finish this part first and then start the bugs and issues here. 

Sorry to mention that in a **BAD** way. I will update it these days. But I think after the **MR**, it can be much easier since they're found while I am using the demo to test.

**Comment by Hearen** [comment]
> I would be better to let the community know your proposal before start contributing.

@ralf0131 Yes, you're right about it. I am proposing a **consistent** demo so the doc can be much easier to follow (especially the commands usage part). 

As I see it, it always would be better if the developer can have a simple try to use the commands to better understand how they can be used. 

That's the root cause/reason that I think it's important to **unify** the demo through the documentation where the developer can easily try the commands when they want to instead of just reading the **unfamiliar** demo, which they cannot touch directly.

**Comment by hengyunabc** [comment]
Thanks for the PR. The doc already updated with `arthas-demo`.  https://alibaba.github.io/arthas/quick-start.html

**Pull request closed without merging**
